#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace cybersand {

// Values 0-19 intentionally preserve the Sandspiel material identifiers for
// imported compositions and palette data. Value 10 was an unused/sink slot in
// the reference project and remains invalid here. Smoke is the project-facing
// name for Sandspiel's Gas value.
enum class Material : std::uint8_t {
    Empty = 0,
    Wall = 1,
    Sand = 2,
    Water = 3,
    Smoke = 4,
    Gas = Smoke,
    Cloner = 5,
    Fire = 6,
    Wood = 7,
    Lava = 8,
    Ice = 9,
    Plant = 11,
    Acid = 12,
    Stone = 13,
    Dust = 14,
    Mite = 15,
    Oil = 16,
    Rocket = 17,
    Fungus = 18,
    Seed = 19,
    Paste = 20,
    Slush = 21,
    Steam = 22,
    Salt = 23,
    Brine = 24,
    Sodium = 25,
    Gunpowder = 26,
    Coal = 27,
    Metal = 28,
    Rust = 29,
    Cement = 30,
    Concrete = 31,
    ToxicSludge = 32,
    Mercury = 33,
    Spark = 34,
    Glass = 35,
    MoltenGlass = 36,
    Foam = 37,
    LimestoneBlock = 38,
    SandstoneBlock = 39,
    GraniteBlock = 40,
    Cobblestone = 41,
    MossyCobblestone = 42,
    RedBrick = 43,
    LimePlaster = 44,
    WattleAndDaub = 45,
    OakTimber = 46,
    Thatch = 47,
    TerracottaTile = 48,
    Slate = 49,
    WroughtIron = 50,
    LeadSheet = 51,
    Bronze = 52,
    Copper = 53,
    VerdigrisCopper = 54,
    StainedGlass = 55,
    PackedEarth = 56,
    IndustrialBrick = 57,
    ReinforcedConcrete = 58,
    Asphalt = 59,
    WetAsphalt = 60,
    WetCobblestone = 61,
    SteelPlate = 62,
    PaintedSteel = 63,
    CorrugatedSteel = 64,
    RustedSteel = 65,
    SteelGrating = 66,
    Chainlink = 67,
    SteelPipe = 68,
    CopperPipe = 69,
    CeramicTile = 70,
    ChemicalGlass = 71,
    DarkGlass = 72,
    Rubber = 73,
    CableBundle = 74,
    Insulation = 75,
    HazardStripe = 76,
    NeonCyan = 77,
    NeonMagenta = 78,
    NeonAmber = 79,
    LedWhite = 80,
};

enum class MaterialState : std::uint8_t {
    Empty,
    Solid,
    Powder,
    Liquid,
    Gas,
    Agent,
};

enum class RuleKernel : std::uint8_t {
    None,
    Sand,
    Water,
    Gas,
    Cloner,
    Fire,
    Combustible,
    Lava,
    Ice,
    Plant,
    Acid,
    Stone,
    Dust,
    Mite,
    Oil,
    Rocket,
    Fungus,
    Seed,
    YieldingLiquid,
    Steam,
    Gunpowder,
    Coal,
    Metal,
    Cement,
    Spark,
    MoltenGlass,
    Foam,
};

// Density exchange is directional and opt-in. A falling material may displace
// a lighter movable material below it; a rising material may displace a
// heavier movable material above it. Keeping this separate from MaterialState
// lets future foams, trapped gases, gels, and pastes decline the exchange even
// when their broad phase would normally suggest it.
enum class DensityMotion : std::uint8_t {
    None,
    Down,
    Up,
};

// FreeMass is the conserved fixed-point Water solver. CellularYield retains
// the intentionally heap-capable, whole-cell movement family used by viscous
// liquids and available to future slush/paste materials.
enum class LateralFlowMode : std::uint8_t {
    None,
    FreeMass,
    CellularYield,
};

struct MaterialDefinition {
    std::string_view name;
    MaterialState state;
    std::uint16_t density;
    std::array<std::uint8_t, 4> rgba;
    bool movable;
    bool valid;
    bool current_rule_available;
    RuleKernel kernel;
    std::uint8_t initial_state_a;
    std::uint8_t initial_state_b;
    std::uint8_t maximum_write_radius;
    DensityMotion density_motion;
    bool accepts_density_exchange;
    LateralFlowMode lateral_flow;
    // Dimensionless gameplay viscosity. Zero is maximally mobile and 255 is
    // the slowest supported liquid. LateralFlowMode::None makes it irrelevant.
    std::uint8_t viscosity_index;
};

inline constexpr std::array<MaterialDefinition, 81> kMaterialDefinitions{{
    {"empty", MaterialState::Empty, 0, {8, 11, 18, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"wall", MaterialState::Solid, 65'535, {82, 91, 106, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"sand", MaterialState::Powder, 1'600, {222, 174, 76, 255}, true, true, true,
     RuleKernel::Sand, 0, 0, 1, DensityMotion::Down, true, LateralFlowMode::None, 0},
    {"water", MaterialState::Liquid, 1'000, {47, 127, 210, 255}, true, true, true,
     RuleKernel::Water, 255, 0, 1, DensityMotion::Down, true, LateralFlowMode::FreeMass, 0},
    {"smoke", MaterialState::Gas, 20, {122, 130, 143, 210}, true, true, true,
     RuleKernel::Gas, 240, 0, 1, DensityMotion::Up, true, LateralFlowMode::None, 0},
    {"cloner", MaterialState::Solid, 65'535, {185, 117, 171, 255}, false, true, true,
     RuleKernel::Cloner, 0, 0, 1, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"fire", MaterialState::Gas, 5, {246, 114, 42, 255}, true, true, true,
     RuleKernel::Fire, 240, 0, 1, DensityMotion::Up, true, LateralFlowMode::None, 0},
    {"wood", MaterialState::Solid, 720, {116, 78, 48, 255}, false, true, true,
     RuleKernel::Combustible, 0, 0, 1, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"lava", MaterialState::Liquid, 2'600, {241, 78, 31, 255}, true, true, true,
     RuleKernel::Lava, 0, 0, 1, DensityMotion::Down, true,
     LateralFlowMode::CellularYield, 224},
    {"ice", MaterialState::Solid, 920, {150, 218, 239, 255}, false, true, true,
     RuleKernel::Ice, 0, 0, 1, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"invalid", MaterialState::Solid, 65'535, {255, 0, 255, 255}, false, false, false,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"plant", MaterialState::Solid, 540, {71, 166, 79, 255}, false, true, true,
     RuleKernel::Plant, 32, 0, 1, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"acid", MaterialState::Liquid, 1'050, {200, 228, 48, 255}, true, true, true,
     RuleKernel::Acid, 255, 0, 1, DensityMotion::Down, true,
     LateralFlowMode::CellularYield, 64},
    {"stone", MaterialState::Powder, 2'400, {126, 126, 132, 255}, true, true, true,
     RuleKernel::Stone, 0, 0, 1, DensityMotion::Down, true, LateralFlowMode::None, 0},
    {"dust", MaterialState::Powder, 420, {218, 198, 238, 255}, true, true, true,
     RuleKernel::Dust, 0, 0, 1, DensityMotion::Down, true, LateralFlowMode::None, 0},
    {"mite", MaterialState::Agent, 620, {207, 76, 221, 255}, true, true, true,
     RuleKernel::Mite, 1, 0, 1, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"oil", MaterialState::Liquid, 800, {75, 67, 72, 255}, true, true, true,
     RuleKernel::Oil, 0, 0, 1, DensityMotion::Down, true,
     LateralFlowMode::CellularYield, 160},
    {"rocket", MaterialState::Agent, 1'300, {244, 220, 215, 255}, true, true, true,
     RuleKernel::Rocket, 0, static_cast<std::uint8_t>(Material::Sand), 2,
     DensityMotion::Down, false, LateralFlowMode::None, 0},
    {"fungus", MaterialState::Solid, 510, {192, 106, 177, 255}, false, true, true,
     RuleKernel::Fungus, 32, 0, 1, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"seed", MaterialState::Powder, 680, {231, 144, 191, 255}, true, true, true,
     RuleKernel::Seed, 0, 0, 1, DensityMotion::Down, true, LateralFlowMode::None, 0},
    {"paste", MaterialState::Liquid, 1'300, {155, 130, 86, 255}, true, true, true,
     RuleKernel::YieldingLiquid, 0, 0, 1, DensityMotion::Down, true,
     LateralFlowMode::CellularYield, 240},
    {"slush", MaterialState::Liquid, 1'080, {115, 186, 207, 255}, true, true, true,
     RuleKernel::YieldingLiquid, 0, 0, 1, DensityMotion::Down, true,
     LateralFlowMode::CellularYield, 192},
    {"steam", MaterialState::Gas, 12, {205, 224, 232, 210}, true, true, true,
     RuleKernel::Steam, 180, 0, 1, DensityMotion::Up, true, LateralFlowMode::None, 0},
    {"salt", MaterialState::Powder, 2'160, {236, 232, 218, 255}, true, true, true,
     RuleKernel::Sand, 0, 0, 1, DensityMotion::Down, true, LateralFlowMode::None, 0},
    {"brine", MaterialState::Liquid, 1'120, {92, 166, 194, 255}, true, true, true,
     RuleKernel::YieldingLiquid, 0, 0, 1, DensityMotion::Down, true,
     LateralFlowMode::CellularYield, 32},
    {"sodium", MaterialState::Powder, 970, {226, 223, 192, 255}, true, true, true,
     RuleKernel::Sand, 0, 0, 1, DensityMotion::Down, true, LateralFlowMode::None, 0},
    {"gunpowder", MaterialState::Powder, 1'700, {69, 61, 57, 255}, true, true, true,
     RuleKernel::Gunpowder, 0, 0, 1, DensityMotion::Down, true, LateralFlowMode::None, 0},
    {"coal", MaterialState::Powder, 1'300, {43, 41, 45, 255}, true, true, true,
     RuleKernel::Coal, 0, 0, 1, DensityMotion::Down, true, LateralFlowMode::None, 0},
    {"metal", MaterialState::Solid, 7'800, {151, 161, 171, 255}, false, true, true,
     RuleKernel::Metal, 0, 0, 1, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"rust", MaterialState::Powder, 5'250, {166, 74, 42, 255}, true, true, true,
     RuleKernel::Sand, 0, 0, 1, DensityMotion::Down, true, LateralFlowMode::None, 0},
    {"cement", MaterialState::Liquid, 2'600, {143, 143, 132, 255}, true, true, true,
     RuleKernel::Cement, 180, 0, 1, DensityMotion::Down, true,
     LateralFlowMode::CellularYield, 176},
    {"concrete", MaterialState::Solid, 2'400, {105, 108, 112, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"toxic-sludge", MaterialState::Liquid, 1'050, {77, 164, 64, 255}, true, true, true,
     RuleKernel::YieldingLiquid, 0, 0, 1, DensityMotion::Down, true,
     LateralFlowMode::CellularYield, 64},
    {"mercury", MaterialState::Liquid, 13'500, {184, 192, 203, 255}, true, true, true,
     RuleKernel::YieldingLiquid, 0, 0, 1, DensityMotion::Down, true,
     LateralFlowMode::CellularYield, 96},
    {"spark", MaterialState::Agent, 2, {255, 232, 91, 255}, true, true, true,
     RuleKernel::Spark, 12, 0, 1, DensityMotion::Up, false, LateralFlowMode::None, 0},
    {"glass", MaterialState::Solid, 2'500, {128, 205, 220, 210}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"molten-glass", MaterialState::Liquid, 2'500, {255, 146, 64, 255}, true, true, true,
     RuleKernel::MoltenGlass, 180, 0, 1, DensityMotion::Down, true,
     LateralFlowMode::CellularYield, 224},
    {"foam", MaterialState::Gas, 6, {232, 243, 225, 220}, true, true, true,
     RuleKernel::Foam, 120, 0, 1, DensityMotion::Up, true, LateralFlowMode::None, 0},
    {"limestone-block", MaterialState::Solid, 2'350, {197, 191, 175, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"sandstone-block", MaterialState::Solid, 2'200, {199, 156, 98, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"granite-block", MaterialState::Solid, 2'700, {119, 119, 130, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"cobblestone", MaterialState::Solid, 2'500, {119, 116, 108, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"mossy-cobblestone", MaterialState::Solid, 2'400, {101, 112, 90, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"red-brick", MaterialState::Solid, 1'900, {163, 80, 59, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"lime-plaster", MaterialState::Solid, 1'650, {210, 205, 185, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"wattle-and-daub", MaterialState::Solid, 1'200, {186, 155, 114, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"oak-timber", MaterialState::Solid, 720, {111, 69, 40, 255}, false, true, true,
     RuleKernel::Combustible, 0, 0, 1, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"thatch", MaterialState::Solid, 120, {180, 147, 73, 255}, false, true, true,
     RuleKernel::Combustible, 0, 0, 1, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"terracotta-tile", MaterialState::Solid, 2'000, {185, 91, 60, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"slate", MaterialState::Solid, 2'750, {70, 83, 99, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"wrought-iron", MaterialState::Solid, 7'800, {50, 58, 64, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"lead-sheet", MaterialState::Solid, 11'340, {105, 115, 125, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"bronze", MaterialState::Solid, 8'800, {162, 113, 56, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"copper", MaterialState::Solid, 8'960, {184, 108, 64, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"verdigris-copper", MaterialState::Solid, 8'600, {79, 140, 121, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"stained-glass", MaterialState::Solid, 2'500, {71, 127, 168, 216}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"packed-earth", MaterialState::Solid, 1'800, {124, 91, 59, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"industrial-brick", MaterialState::Solid, 1'950, {116, 63, 54, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"reinforced-concrete", MaterialState::Solid, 2'500, {119, 123, 128, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"asphalt", MaterialState::Solid, 2'300, {41, 45, 50, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"wet-asphalt", MaterialState::Solid, 2'300, {21, 28, 36, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"wet-cobblestone", MaterialState::Solid, 2'500, {65, 74, 78, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"steel-plate", MaterialState::Solid, 7'850, {126, 141, 153, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"painted-steel", MaterialState::Solid, 7'850, {49, 100, 119, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"corrugated-steel", MaterialState::Solid, 7'850, {109, 125, 134, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"rusted-steel", MaterialState::Solid, 7'200, {124, 63, 43, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"steel-grating", MaterialState::Solid, 7'850, {74, 85, 93, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"chainlink", MaterialState::Solid, 7'850, {101, 116, 123, 208}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"steel-pipe", MaterialState::Solid, 7'850, {102, 119, 129, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"copper-pipe", MaterialState::Solid, 8'960, {165, 92, 54, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"ceramic-tile", MaterialState::Solid, 2'300, {200, 210, 203, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"chemical-glass", MaterialState::Solid, 2'500, {107, 196, 181, 184}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"dark-glass", MaterialState::Solid, 2'500, {37, 60, 76, 192}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"rubber", MaterialState::Solid, 1'100, {36, 37, 41, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"cable-bundle", MaterialState::Solid, 1'500, {60, 53, 68, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"insulation", MaterialState::Solid, 120, {214, 197, 92, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"hazard-stripe", MaterialState::Solid, 7'850, {227, 182, 47, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"neon-cyan", MaterialState::Solid, 2'500, {55, 243, 228, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"neon-magenta", MaterialState::Solid, 2'500, {255, 61, 184, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"neon-amber", MaterialState::Solid, 2'500, {255, 181, 46, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
    {"led-white", MaterialState::Solid, 2'500, {236, 248, 255, 255}, false, true, true,
     RuleKernel::None, 0, 0, 0, DensityMotion::None, false, LateralFlowMode::None, 0},
}};

[[nodiscard]] constexpr const MaterialDefinition& material_definition(Material material) noexcept {
    const auto index = static_cast<std::size_t>(material);
    return index < kMaterialDefinitions.size() ? kMaterialDefinitions[index] : kMaterialDefinitions[10];
}

[[nodiscard]] constexpr bool valid_material(std::uint16_t value) noexcept {
    return value < kMaterialDefinitions.size() && kMaterialDefinitions[value].valid;
}

static_assert(sizeof(Material) == 1, "material identifiers must remain byte-sized");

}  // namespace cybersand
